{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-ballerina.secretName" . }}
  labels:
    {{- include "mcp-ballerina.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
  annotations:
    {{- include "mcp-ballerina.annotations" . | nindent 4 }}
    description: "Sensitive configuration for MCP Ballerina Server"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
type: Opaque
data:
  # Database credentials (base64 encoded)
  database-url: {{ include "mcp-ballerina.databaseUrl" . | b64enc | quote }}
  database-username: {{ .Values.secrets.database.username | b64enc | quote }}
  database-password: {{ .Values.secrets.database.password | b64enc | quote }}
  
  # Redis credentials
  redis-url: {{ include "mcp-ballerina.redisUrl" . | b64enc | quote }}
  redis-password: {{ .Values.secrets.redis.password | b64enc | quote }}
  
  # API Keys and tokens
  api-key: {{ .Values.secrets.api.key | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.api.jwtSecret | b64enc | quote }}
  encryption-key: {{ .Values.secrets.api.encryptionKey | b64enc | quote }}
  
  # External service credentials
  oauth-client-id: {{ .Values.secrets.oauth.clientId | b64enc | quote }}
  oauth-client-secret: {{ .Values.secrets.oauth.clientSecret | b64enc | quote }}
{{- end }}