filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

- type: log
  enabled: true
  paths:
    - /var/log/mcp/*.log
  fields:
    service: mcp-ballerina
    environment: production
  fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "mcp-ballerina-%{+yyyy.MM.dd}"

setup.template.name: "mcp-ballerina"
setup.template.pattern: "mcp-ballerina-*"
setup.template.enabled: true

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644