global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: 'mcp-ballerina-dev'
    environment: 'development'

scrape_configs:
  - job_name: 'mcp-ballerina-dev'
    static_configs:
      - targets: ['mcp-ballerina-dev:9090']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s
    
  - job_name: 'prometheus-dev'
    static_configs:
      - targets: ['localhost:9090']