apiVersion: v1
kind: Namespace
metadata:
  name: mcp-ballerina
  labels:
    name: mcp-ballerina
    environment: production
    app.kubernetes.io/name: mcp-ballerina
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: mcp-ballerina
    app.kubernetes.io/managed-by: gitops
  annotations:
    description: "MCP Ballerina Server Namespace"
    contact: "platform-team@company.com"
    gitops.argoproj.io/sync-wave: "-5"
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-ballerina-quota
  namespace: mcp-ballerina
  labels:
    app.kubernetes.io/name: mcp-ballerina
    app.kubernetes.io/component: resource-quota
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mcp-ballerina-limits
  namespace: mcp-ballerina
  labels:
    app.kubernetes.io/name: mcp-ballerina
    app.kubernetes.io/component: limit-range
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim