apiVersion: v1
kind: Secret
metadata:
  name: mcp-ballerina-secrets
  namespace: mcp-ballerina
  labels:
    app.kubernetes.io/name: mcp-ballerina
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: mcp-ballerina
    app.kubernetes.io/managed-by: gitops
  annotations:
    description: "Sensitive configuration for MCP Ballerina Server"
    gitops.argoproj.io/sync-wave: "-2"
type: Opaque
data:
  # Database credentials (base64 encoded)
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bsb2NhbGhvc3Q6NTQzMi9tY3BfYmFsbGVyaW5h
  database-username: bWNwX3VzZXI=
  database-password: Y2hhbmdlX21lX3Byb2R1Y3Rpb24=
  
  # Redis credentials
  redis-url: cmVkaXM6Ly86Y2hhbmdlX21lQGxvY2FsaG9zdDo2Mzc5LzA=
  redis-password: Y2hhbmdlX21lX3JlZGlz
  
  # API Keys and tokens
  api-key: YWJjZGVmZ2hpams=
  jwt-secret: c3VwZXJfc2VjcmV0X2p3dF9rZXlfY2hhbmdlX21l
  encryption-key: ZW5jcnlwdGlvbl9rZXlfMzJfYnl0ZXNfbG9uZw==
  
  # External service credentials
  oauth-client-id: Y2xpZW50XzEyMzQ1
  oauth-client-secret: c2VjcmV0XzY3ODkw
  
  # TLS certificates (if not using cert-manager)
  tls-cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  tls-key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
---
apiVersion: v1
kind: Secret
metadata:
  name: mcp-ballerina-tls
  namespace: mcp-ballerina
  labels:
    app.kubernetes.io/name: mcp-ballerina
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: mcp-ballerina
  annotations:
    description: "TLS certificates for MCP Ballerina Server"
    cert-manager.io/issuer: "letsencrypt-prod"
type: kubernetes.io/tls
data:
  # These would be populated by cert-manager or external certificate management
  tls.crt: ""
  tls.key: ""
---
# External Secrets Operator integration (optional)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mcp-ballerina-vault
  namespace: mcp-ballerina
  labels:
    app.kubernetes.io/name: mcp-ballerina
    app.kubernetes.io/component: secret-store
spec:
  provider:
    vault:
      server: "https://vault.company.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "mcp-ballerina"
          serviceAccountRef:
            name: mcp-ballerina
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-ballerina-external
  namespace: mcp-ballerina
  labels:
    app.kubernetes.io/name: mcp-ballerina
    app.kubernetes.io/component: external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: mcp-ballerina-vault
    kind: SecretStore
  target:
    name: mcp-ballerina-vault-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-password
    remoteRef:
      key: mcp-ballerina/database
      property: password
  - secretKey: api-key
    remoteRef:
      key: mcp-ballerina/api
      property: key
  - secretKey: jwt-secret
    remoteRef:
      key: mcp-ballerina/auth
      property: jwt_secret