groups:
  - name: mcp-ballerina-alerts
    interval: 30s
    rules:
      # Application alerts
      - alert: MCPBallerinaDown
        expr: up{job="mcp-ballerina"} == 0
        for: 5m
        labels:
          severity: critical
          service: mcp-ballerina
        annotations:
          summary: "MCP Ballerina server is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

      - alert: HighErrorRate
        expr: |
          (
            sum(rate(mcp_ballerina_errors_total[5m])) by (job, instance)
            /
            sum(rate(mcp_ballerina_requests_total[5m])) by (job, instance)
          ) > 0.05
        for: 10m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, 
            sum(rate(mcp_ballerina_request_duration_seconds_bucket[5m])) by (le, job, instance)
          ) > 1
        for: 10m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"

      - alert: LowCacheHitRate
        expr: |
          (
            sum(rate(mcp_ballerina_cache_hits_total[5m])) by (job, instance)
            /
            sum(rate(mcp_ballerina_cache_requests_total[5m])) by (job, instance)
          ) < 0.7
        for: 15m
        labels:
          severity: info
          service: mcp-ballerina
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # Resource alerts
      - alert: HighMemoryUsage
        expr: |
          (
            container_memory_working_set_bytes{pod=~"mcp-ballerina.*"}
            / 
            container_spec_memory_limit_bytes{pod=~"mcp-ballerina.*"}
          ) > 0.8
        for: 10m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} for pod {{ $labels.pod }}"

      - alert: HighCPUUsage
        expr: |
          (
            sum(rate(container_cpu_usage_seconds_total{pod=~"mcp-ballerina.*"}[5m])) by (pod)
            /
            sum(container_spec_cpu_quota{pod=~"mcp-ballerina.*"}/container_spec_cpu_period{pod=~"mcp-ballerina.*"}) by (pod)
          ) > 0.8
        for: 10m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value | humanizePercentage }} for pod {{ $labels.pod }}"

      - alert: PodRestartingTooOften
        expr: |
          rate(kube_pod_container_status_restarts_total{namespace="mcp-ballerina"}[1h]) > 0.5
        for: 5m
        labels:
          severity: critical
          service: mcp-ballerina
        annotations:
          summary: "Pod restarting too often"
          description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last hour"

      # Database alerts
      - alert: DatabaseConnectionPoolExhausted
        expr: |
          mcp_ballerina_db_connections_active / mcp_ballerina_db_connections_max > 0.9
        for: 5m
        labels:
          severity: critical
          service: mcp-ballerina
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Database connection pool is {{ $value | humanizePercentage }} full"

      - alert: SlowDatabaseQueries
        expr: |
          histogram_quantile(0.95,
            sum(rate(mcp_ballerina_db_query_duration_seconds_bucket[5m])) by (le)
          ) > 2
        for: 10m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile database query time is {{ $value }}s"

      # Security alerts
      - alert: HighAuthenticationFailureRate
        expr: |
          sum(rate(mcp_ballerina_auth_failures_total[5m])) > 10
        for: 5m
        labels:
          severity: warning
          service: mcp-ballerina
          security: true
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value }} per second"

      - alert: SuspiciousAPIActivity
        expr: |
          sum(rate(mcp_ballerina_suspicious_requests_total[5m])) by (source_ip) > 5
        for: 5m
        labels:
          severity: critical
          service: mcp-ballerina
          security: true
        annotations:
          summary: "Suspicious API activity detected"
          description: "Suspicious activity from IP {{ $labels.source_ip }} - {{ $value }} requests per second"

      # Performance alerts
      - alert: HighGCPauseTime
        expr: |
          mcp_ballerina_gc_pause_seconds{quantile="0.95"} > 0.5
        for: 10m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "High GC pause time"
          description: "95th percentile GC pause time is {{ $value }}s"

      - alert: ThreadPoolExhausted
        expr: |
          mcp_ballerina_thread_pool_active / mcp_ballerina_thread_pool_max > 0.9
        for: 5m
        labels:
          severity: critical
          service: mcp-ballerina
        annotations:
          summary: "Thread pool nearly exhausted"
          description: "Thread pool is {{ $value | humanizePercentage }} full"

      # Collaboration alerts
      - alert: WebSocketConnectionsHigh
        expr: |
          mcp_ballerina_websocket_connections > 1000
        for: 10m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "High number of WebSocket connections"
          description: "{{ $value }} WebSocket connections active"

      - alert: CollaborationSyncFailures
        expr: |
          sum(rate(mcp_ballerina_collaboration_sync_failures_total[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "Collaboration sync failures detected"
          description: "Sync failure rate is {{ $value }} per second"

      # Storage alerts
      - alert: PersistentVolumeSpaceLow
        expr: |
          (
            kubelet_volume_stats_available_bytes{namespace="mcp-ballerina"}
            /
            kubelet_volume_stats_capacity_bytes{namespace="mcp-ballerina"}
          ) < 0.1
        for: 5m
        labels:
          severity: critical
          service: mcp-ballerina
        annotations:
          summary: "Persistent volume space low"
          description: "Only {{ $value | humanizePercentage }} space left on {{ $labels.persistentvolumeclaim }}"

      # Service mesh alerts
      - alert: HighLatencyBetweenServices
        expr: |
          histogram_quantile(0.95,
            sum(rate(istio_request_duration_milliseconds_bucket{destination_service_namespace="mcp-ballerina"}[5m])) by (le, source_app, destination_app)
          ) > 1000
        for: 10m
        labels:
          severity: warning
          service: mcp-ballerina
        annotations:
          summary: "High latency between services"
          description: "95th percentile latency from {{ $labels.source_app }} to {{ $labels.destination_app }} is {{ $value }}ms"