name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-ballerina-dependencies:
    name: Update Ballerina Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Update dependencies
        run: |
          cd ballerina-mcp-server
          
          # Backup current Dependencies.toml
          cp Dependencies.toml Dependencies.toml.backup
          
          # Update dependencies
          bal update
          
          # Check if there are any changes
          if ! cmp -s Dependencies.toml Dependencies.toml.backup; then
            echo "Dependencies updated"
            echo "DEPENDENCIES_UPDATED=true" >> $GITHUB_ENV
          else
            echo "No dependency updates available"
            echo "DEPENDENCIES_UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Run tests after update
        if: env.DEPENDENCIES_UPDATED == 'true'
        run: |
          cd ballerina-mcp-server
          bal build
          bal test

      - name: Create Pull Request
        if: env.DEPENDENCIES_UPDATED == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update Ballerina dependencies'
          title: 'chore(deps): Update Ballerina dependencies'
          body: |
            ## Automated Dependency Update
            
            This PR updates Ballerina dependencies to their latest versions.
            
            ### Changes
            - Updated `Dependencies.toml` with latest package versions
            - All tests pass with updated dependencies
            
            ### Verification
            - [x] Build passes
            - [x] Tests pass
            - [ ] Manual verification (if needed)
            
            This PR was automatically created by the dependency update workflow.
          branch: chore/update-ballerina-dependencies
          delete-branch: true
          labels: |
            dependencies
            automated
            chore

  update-github-actions:
    name: Update GitHub Actions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update GitHub Actions versions
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const workflowDir = '.github/workflows';
            const workflows = fs.readdirSync(workflowDir);
            
            let updated = false;
            
            for (const workflow of workflows) {
              if (!workflow.endsWith('.yml') && !workflow.endsWith('.yaml')) continue;
              
              const filePath = path.join(workflowDir, workflow);
              let content = fs.readFileSync(filePath, 'utf8');
              
              // Update common actions to latest versions
              const updates = [
                { from: 'actions/checkout@v3', to: 'actions/checkout@v4' },
                { from: 'actions/setup-node@v3', to: 'actions/setup-node@v4' },
                { from: 'actions/cache@v3', to: 'actions/cache@v4' },
                { from: 'docker/login-action@v2', to: 'docker/login-action@v3' },
                { from: 'docker/build-push-action@v4', to: 'docker/build-push-action@v5' }
              ];
              
              let fileUpdated = false;
              for (const update of updates) {
                if (content.includes(update.from)) {
                  content = content.replace(new RegExp(update.from, 'g'), update.to);
                  fileUpdated = true;
                  updated = true;
                }
              }
              
              if (fileUpdated) {
                fs.writeFileSync(filePath, content);
                console.log(`Updated ${workflow}`);
              }
            }
            
            core.setOutput('updated', updated);

      - name: Create Pull Request for Actions Updates
        if: steps.update-actions.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(ci): update GitHub Actions to latest versions'
          title: 'chore(ci): Update GitHub Actions to latest versions'
          body: |
            ## Automated GitHub Actions Update
            
            This PR updates GitHub Actions to their latest versions for better security and performance.
            
            ### Changes
            - Updated action versions in workflow files
            - All workflows should continue to work as expected
            
            ### Verification
            - [ ] All workflows run successfully
            - [ ] No breaking changes introduced
            
            This PR was automatically created by the dependency update workflow.
          branch: chore/update-github-actions
          delete-branch: true
          labels: |
            ci/cd
            automated
            chore

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Run security audit
        run: |
          cd ballerina-mcp-server
          echo "Running security audit on dependencies..."
          
          # Check for known vulnerabilities in dependencies
          bal pull
          
          # Create security report
          echo "# Security Audit Report" > security-audit.md
          echo "" >> security-audit.md
          echo "Generated on: $(date)" >> security-audit.md
          echo "" >> security-audit.md
          
          echo "## Dependencies" >> security-audit.md
          if [ -f "Dependencies.toml" ]; then
            cat Dependencies.toml >> security-audit.md
          fi

      - name: Upload security audit report
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-report
          path: ballerina-mcp-server/security-audit.md

      - name: Create security issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔒 Security vulnerabilities detected in dependencies',
              body: `Security audit found potential vulnerabilities in project dependencies.
              
              Please review the security audit report and update vulnerable dependencies.
              
              Audit run: ${context.runId}
              Date: ${new Date().toISOString()}
              `,
              labels: ['security', 'high-priority', 'automated']
            })

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
          deny-licenses: GPL-2.0, GPL-3.0

      - name: Comment on PR
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const output = `
            ## 📦 Dependency Review
            
            Dependency review completed for this PR.
            
            - ✅ License compliance checked
            - ✅ Security vulnerabilities scanned
            - ✅ Supply chain security verified
            
            See the dependency review action results above for details.
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })